export interface Product {
  id: string; // Firestore document ID
  name: string;
  description: string;
  price: number;
  imageUrl: string;
}

// Used for form data when creating a new product, ID is auto-generated by Firestore
export type ProductFormData = Omit<Product, 'id'>;
